export type Distributor = {
  city: string;
  state: string;
  name: string;
  colonia?: string;
  phone: string;
  web?: string;
};

export const STATE_ORDER = [
  "JALISCO",
  "NAYARIT",
  "COLIMA",
  "MICHOACAN",
  "GUANAJUATO",
  "QUERETARO",
  "ESTADO DE MEXICO",
  "GUERRERO",
  "ZACATECAS",
];

export const DISTRIBUTORS: Distributor[] = [
  {
    city: "TEQUILA",
    state: "JALISCO",
    name: "FHEGARSA",
    colonia: "",
    phone: "374 742 1169",
    web: "fhegarsa.mx",
  },
  {
    city: "ETZATLAN",
    state: "JALISCO",
    name: "MATERIALES AVIÑA",
    colonia: "",
    phone: "386 753 0922",
    web: "",
  },
  {
    city: "TEPIC",
    state: "NAYARIT",
    name: "ACEROS BUGAMBILIA TEPIC",
    colonia: "",
    phone: "311 213 7758",
    web: "acerosbugambilia.com",
  },
  {
    city: "LA PEÑITA",
    state: "NAYARIT",
    name: "FERRETERIA KORANAY",
    colonia: "",
    phone: "327 274 0041",
    web: "",
  },
  {
    city: "PTO. VALLARTA",
    state: "JALISCO",
    name: "MATERIALES LIVIANOS CYL",
    colonia: "",
    phone: "322 252 1844",
    web: "materialeslivianos.com",
  },
  {
    city: "PTO. VALLARTA",
    state: "JALISCO",
    name: "MATERIALES LA VENA",
    colonia: "",
    phone: "322 299 0165",
    web: "",
  },
  {
    city: "PTO. VALLARTA",
    state: "JALISCO",
    name: "PRODUCTOS MADERABLES DE CUALE",
    colonia: "",
    phone: "322 299 1824",
    web: "maderasdecuale.com",
  },
  {
    city: "PTO. VALLARTA",
    state: "JALISCO",
    name: "MATERIALES VILLASEÑOR",
    colonia: "",
    phone: "322 307 4147",
    web: "",
  },
  {
    city: "PTO. VALLARTA",
    state: "JALISCO",
    name: "FERRETERIA RODRIGUEZ DE VALLARTA",
    colonia: "",
    phone: "322 224 8400",
    web: "",
  },
  {
    city: "PTO. VALLARTA",
    state: "JALISCO",
    name: "ACEROS OCOTLAN",
    colonia: "",
    phone: "322 226 2600",
    web: "acerosocotlan.mx",
  },
  {
    city: "CD. GUZMAN",
    state: "JALISCO",
    name: "POLILAMINAS D'ALBA",
    colonia: "",
    phone: "341 412 2223",
    web: "",
  },
  {
    city: "CD. GUZMAN",
    state: "JALISCO",
    name: "CONSTRUKASA",
    colonia: "",
    phone: "341 100 9002",
    web: "",
  },
  {
    city: "CD. GUZMAN",
    state: "JALISCO",
    name: "ACEROS OCOTLAN",
    colonia: "",
    phone: "341 413 3180",
    web: "acerosocotlan.mx",
  },
  {
    city: "ZAPOTILTIC",
    state: "JALISCO",
    name: "ATC SUR DE JALISCO",
    colonia: "",
    phone: "341 358 1244",
    web: "atcmexico.com",
  },
  {
    city: "SOYATLAN",
    state: "JALISCO",
    name: "DISENSA SOYATLAN",
    colonia: "",
    phone: "33 2255 4806",
    web: "disensa.mx",
  },
  {
    city: "TAMAZULA",
    state: "JALISCO",
    name: "MATERIALES VARGAS",
    colonia: "",
    phone: "358 416 1051",
    web: "",
  },
  {
    city: "TAMAZULA",
    state: "JALISCO",
    name: "MATERIALES DON GERO",
    colonia: "",
    phone: "341 117 6499",
    web: "",
  },
  {
    city: "COLIMA",
    state: "COLIMA",
    name: "CONSORCIO FERRETERO",
    colonia: "",
    phone: "312 313 9110",
    web: "",
  },
  {
    city: "COLIMA",
    state: "COLIMA",
    name: "QUIROZ IMPERMEABILIZANTES",
    colonia: "",
    phone: "312 313 5790",
    web: "quirozfester.com.mx",
  },
  {
    city: "ARMERIA",
    state: "COLIMA",
    name: "FERREMATERIALES VERDUZCO DE ARMERIA",
    colonia: "",
    phone: "313 322 0060",
    web: "",
  },
  {
    city: "MANZANILLO",
    state: "COLIMA",
    name: "MATERIALES LA CENTRAL",
    colonia: "",
    phone: "314 332 5070",
    web: "",
  },
  {
    city: "MANZANILLO",
    state: "COLIMA",
    name: "MATERIALES SANCHEZ",
    colonia: "",
    phone: "314 334 3746",
    web: "",
  },
  {
    city: "MANZANILLO",
    state: "COLIMA",
    name: "QUIROZ IMPERMEABILIZANTES",
    colonia: "",
    phone: "314 333 0023",
    web: "quirozfester.com.mx",
  },
  {
    city: "MANZANILLO",
    state: "COLIMA",
    name: "MATERIALES MONTERREY",
    colonia: "",
    phone: "314 33 0899",
    web: "",
  },
  {
    city: "CIHUATLAN",
    state: "JALISCO",
    name: "MATERIALES EL POLLO CIHUATLAN",
    colonia: "",
    phone: "315 355 2555",
    web: "",
  },
  {
    city: "MELAQUE",
    state: "JALISCO",
    name: "MATERIALES EL POLLO MELAQUE",
    colonia: "",
    phone: "315 355 5598",
    web: "",
  },
  {
    city: "MELAQUE",
    state: "JALISCO",
    name: "FERRETERIA Y MATERIALES JALISCO",
    colonia: "",
    phone: "315 355 5986",
    web: "",
  },
  {
    city: "AGUACALIENTE",
    state: "JALISCO",
    name: "FERREMATERIALES EL POLLO",
    colonia: "",
    phone: "315 112 5319",
    web: "",
  },
  {
    city: "ZAPATA",
    state: "JALISCO",
    name: "MATERIALES EL POLLO",
    colonia: "",
    phone: "315 351 0085",
    web: "",
  },
  {
    city: "TAPALPA",
    state: "JALISCO",
    name: "ACEROS BUGAMBILIA TAPALPA",
    colonia: "",
    phone: "343 432 1226",
    web: "acerosbugambilia.com",
  },
  {
    city: "EL GRULLO",
    state: "JALISCO",
    name: "FERRETERIA Y MATERIALES EL BOSQUE",
    colonia: "",
    phone: "321 387 3433",
    web: "ferreteriaymaterialeselbosque.com.mx",
  },
  {
    city: "EL GRULLO",
    state: "JALISCO",
    name: "ACEROS Y TUBULARES DE LA COSTA",
    colonia: "",
    phone: "321 387 0404",
    web: "atcmexico.mx",
  },
  {
    city: "AUTLAN",
    state: "JALISCO",
    name: "MATERIALES CHAVEZ",
    colonia: "",
    phone: "317 381 1091",
    web: "",
  },
  {
    city: "AUTLAN",
    state: "JALISCO",
    name: "ACEROS Y MATERIALES CHAVEZ",
    colonia: "",
    phone: "317 119 9922",
    web: "",
  },
  {
    city: "AUTLAN",
    state: "JALISCO",
    name: "ACEROS Y TUBULARES DE LA COSTA",
    colonia: "",
    phone: "317 381 0084",
    web: "atcmexico.mx",
  },
  {
    city: "UNION DE TULA",
    state: "JALISCO",
    name: "ACEROS Y MATERIALES CHAVEZ",
    colonia: "",
    phone: "316 371 1777",
    web: "",
  },
  {
    city: "UNION DE TULA",
    state: "JALISCO",
    name: "ACEROS Y TUBULARES DE LA COSTA",
    colonia: "",
    phone: "316 371 1991",
    web: "actmexico.mx",
  },
  {
    city: "TECOLOTLAN",
    state: "JALISCO",
    name: "ACEROS Y TUBULARES DE LA COSTA",
    colonia: "",
    phone: "349 688 0483",
    web: "atcmexico.mx",
  },
  {
    city: "TENAMAXTLAN",
    state: "JALISCO",
    name: "ACEROS Y MATERIALES CHAVEZ",
    colonia: "",
    phone: "349 775 0062",
    web: "ueniweb.com",
  },
  {
    city: "TENAMAXTLAN",
    state: "JALISCO",
    name: "MATERIALES GONZALEZ",
    colonia: "",
    phone: "375 105 0434",
    web: "",
  },
  {
    city: "AMECA",
    state: "JALISCO",
    name: "ACEROS BUGAMBILIA",
    colonia: "",
    phone: "375 758 4755",
    web: "acerosbugambilia.com",
  },
  {
    city: "COCULA",
    state: "JALISCO",
    name: "ACEROS OCOTLAN",
    colonia: "",
    phone: "377 773 3222",
    web: "acerosocotlan.mx",
  },
  {
    city: "COTIJA DE LA PAZ",
    state: "MICHOACAN",
    name: "MATERIALES BECERRA",
    colonia: "",
    phone: "394 534 3058",
    web: "",
  },
  {
    city: "COTIJA DE LA PAZ",
    state: "MICHOACAN",
    name: "PEGADURO",
    colonia: "",
    phone: "394 534 3069",
    web: "pegaduro.com.mx",
  },
  {
    city: "SAHUAYO",
    state: "MICHOACAN",
    name: "PEGADURO",
    colonia: "",
    phone: "353 532 4758",
    web: "pegaduro.com.mx",
  },
  {
    city: "OCOTLAN",
    state: "JALISCO",
    name: "MATERIALES EL TRIANGULO (RENE TORRES)",
    colonia: "",
    phone: "392 922 1599",
    web: "wa.me",
  },
  {
    city: "JOCOTEPEC",
    state: "JALISCO",
    name: "ACEROS BUGAMBILIA JOCOTEPEC",
    colonia: "",
    phone: "33 4161 0010",
    web: "acerosbugambilia.com",
  },
  {
    city: "PEGUEROS",
    state: "JALISCO",
    name: "FERRETERIA Y MATERIALES SAGRADO CORAZON",
    colonia: "",
    phone: "378 717 0458",
    web: "",
  },
  {
    city: "SAN JUAN DE LOS LAGOS",
    state: "JALISCO",
    name: "MATERIALES EL PEDREGAL",
    colonia: "",
    phone: "395 725 7744",
    web: "",
  },
  {
    city: "CAPILLA DE GUADALUPE",
    state: "JALISCO",
    name: "UNIFERRE DE LOS ALTOS",
    colonia: "",
    phone: "378 712 1717",
    web: "uniferre.com",
  },
  {
    city: "PENJAMO",
    state: "GUANAJUATO",
    name: "MATERIALES MARISOL",
    colonia: "",
    phone: "469 692 1628",
    web: "",
  },
  {
    city: "IRAPUATO",
    state: "GUANAJUATO",
    name: "PLACA Y ACERO DEL VALLE",
    colonia: "",
    phone: "33 2620 2692",
    web: "",
  },
  {
    city: "QUERETARO",
    state: "QUERETARO",
    name: "PANEL CONSTRUCCION",
    colonia: "",
    phone: "442 216 8640",
    web: "",
  },
  {
    city: "ATLACOMULCO",
    state: "ESTADO DE MEXICO",
    name: "CENTRAL DE CEMENTO Y VARILLA DE ATLACOMULCO",
    colonia: "",
    phone: "712 122 2051",
    web: "",
  },
  {
    city: "ZIHUATANEJO",
    state: "GUERRERO",
    name: "MATERIALES SAN JERONIMO",
    colonia: "",
    phone: "755 554 5480",
    web: "",
  },
  {
    city: "TLALTENANGO",
    state: "ZACATECAS",
    name: "ACEROS MIRADOR",
    colonia: "",
    phone: "437 954 1784",
    web: "",
  },
  {
    city: "TLALTENANGO",
    state: "ZACATECAS",
    name: "CONSTRURAMA AZTECASA",
    colonia: "",
    phone: "437 954 1966",
    web: "",
  },
  {
    city: "TLALTENANGO",
    state: "ZACATECAS",
    name: "ACEROS Y MATERIALES CAMPOS",
    colonia: "",
    phone: "437 688 2107",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CAOSA",
    colonia: "TESISTA",
    phone: "33 3165 8085",
    web: "caosa.com.mx",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA TONALTECAS",
    colonia: "VALLA IMPERIA",
    phone: "33 2239 7528",
    web: "construrama.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "JIRE HOME",
    colonia: "VICENTE GUERRERO",
    phone: "33 3624 2104",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "SURTEK STORE SARE",
    colonia: "LA VENTA DEL ASTILLERO",
    phone: "33 3280 7914",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "ACEROS BUGAMBILIA",
    colonia: "JARDINES DEL VALLE",
    phone: "33 3365 7373",
    web: "acerosbugambilia.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "SERVIOBRA AVIACION",
    colonia: "SAN JUAN DE OCOTAN",
    phone: "33 3110 1857",
    web: "linktr.ee",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA TONALTECAS",
    colonia: "JARDIN REAL",
    phone: "33 1371 3276",
    web: "construrama.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "DIMACSA",
    colonia: "EL COLLI",
    phone: "33 3110 6700",
    web: "dimacsa.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "MATERIALES LIVIANOS COSS Y LEON",
    colonia: "LOPEZ MATEOS",
    phone: "33 3283 5500",
    web: "materialeslivianos.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "ACEROS Y ALUMINIOS SANTA ANITA",
    colonia: "",
    phone: "33 3686 1412",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "ACEROS BUGAMBILIA",
    colonia: "TLAQUEPAQUE",
    phone: "33 4171 1711",
    web: "acerosbugambilia.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CAOSA",
    colonia: "TOLUQUILLA",
    phone: "33 3689 7428",
    web: "caosa.com.mx",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "MATERIALES SANTA CRUZ",
    colonia: "LOS SAUCES",
    phone: "33 1380 8954",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CAOSA",
    colonia: "AEROPUERTO",
    phone: "33 3695 2138",
    web: "caosa.com.mx",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "MATCO PERIFERICO",
    colonia: "LA DURAZNERA",
    phone: "33 3659 0714",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "TODO DE PANEL",
    colonia: "LAZARO CARDENAS",
    phone: "33 2957 6443",
    web: "tododepanel.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRUKTABLA",
    colonia: "RIO NILO",
    phone: "33 1728 6298",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA TONALTECAS",
    colonia: "TONALA CENTRO",
    phone: "33 1187 0395",
    web: "tonaltecas.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA TONALTECAS",
    colonia: "PERIFERICO ORIENTE",
    phone: "33 1187 0429",
    web: "tonaltecas.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "FERRETERIA INDEPENDENCIA",
    colonia: "",
    phone: "33 3160 5907",
    web: "ferreteria-independencia.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "PROAJSA",
    colonia: "LA JALISCO",
    phone: "33 3607 4291",
    web: "proajsa.mx",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA LEDEZMA",
    colonia: "EL BETEL",
    phone: "33 3604 3459",
    web: "construramaledezma.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA LEDEZMA",
    colonia: "HUENTITAN EL BAJO",
    phone: "33 1837 0210",
    web: "construyeconledezma.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CONSTRURAMA LEDEZMA",
    colonia: "JUAN PABLO II",
    phone: "33 3651 1433",
    web: "construramaledezma.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "CHATARRAL ACEROS",
    colonia: "SAN JUAN BOSCO",
    phone: "33 2786 6926",
    web: "acerosgdl.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "MATERIALES PLASCENCIA",
    colonia: "REPUBLICA",
    phone: "33 3643 1357",
    web: "",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "PIEDRA DE MARMOL",
    colonia: "MEZQUITAN",
    phone: "33 1306 0566",
    web: "piedrademarmol.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "MATERIALES LIVIANOS COSS Y LEON",
    colonia: "AVILA CAMACHO",
    phone: "33 3819 5500",
    web: "materialeslivianos.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "MATERIALES LIVIANOS COSS Y LEON",
    colonia: "COLON",
    phone: "33 3646 5395",
    web: "materialeslivianos.com",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "NAPRESA",
    colonia: "8 DE JULIO",
    phone: "33 3144 8180",
    web: "napresa.com.mx",
  },
  {
    city: "GUADALAJARA",
    state: "JALISCO",
    name: "ACEROS OCOTLAN",
    colonia: "LAZARO CARDENAS",
    phone: "33 3884 1300",
    web: "acerosocotlan.mx",
  },
];
